/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Pfpassport } from "./Pfpassport";
export * as factories from "./factories";
export { Pfpassport__factory } from "./factories/Pfpassport__factory";
